fastlane_require 'dotenv'

before_all do
  Dotenv.overload('.env')
end

platform :android do
  desc "RN Production App"
  lane :distribute do
    # gradle(task: '', project_dir: '', print_command: false, properties: {})
    gradle(task: 'clean assembleRelease', project_dir: './android', print_command: false, properties: {
      "MYAPP_UPLOAD_STORE_FILE" => ENV["MYAPP_UPLOAD_STORE_FILE"],
      "MYAPP_UPLOAD_STORE_PASSWORD" => ENV["MYAPP_UPLOAD_STORE_PASSWORD"],
      "MYAPP_UPLOAD_KEY_ALIAS" => ENV["MYAPP_UPLOAD_KEY_ALIAS"],
      "MYAPP_UPLOAD_KEY_PASSWORD" => ENV["MYAPP_UPLOAD_KEY_PASSWORD"]
    })

    firebase_app_distribution(
      app: "1:141573087725:android:6f7e3d3dd379a03c5bc7e4",
      testers: "sairanjit5@gmail.com, sairanjittummalapalli@ayanworks.com",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      release_notes: "Lots of amazing new features to test out!"
    )
  end
end